"use client"
import { useEffect, useMemo, useState } from "react"
import Link from "next/link"
import { useParams } from "next/navigation"
import { useAuth } from "@/contexts/AuthContext"
import { assetUrl, fetchConnections, fetchProjects, fetchUserById, recordProfileView, requestConnection } from "@/lib/api"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Code2, MapPin, Calendar, Github, Linkedin, Globe, Twitter, Briefcase, UserPlus, UserCheck, Clock3, MessageSquare } from "lucide-react"
import { formatLocalDateTime } from "@/lib/time"

const safeUrl=(v?:string)=>{const r=String(v||"").trim();if(!r)return"";const u=r.startsWith("http")?r:`https://${r}`;try{const x=new URL(u);return ["http:","https:"].includes(x.protocol)?x.toString():""}catch{return""}}

export default function PublicProfilePage(){
 const params=useParams<{id:string}>(); const {user,token,isLoading}=useAuth(); const id=String(params?.id||"")
 const [person,setPerson]=useState<any>(); const [projects,setProjects]=useState<any[]>([]); const [connections,setConnections]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState("")
 useEffect(()=>{if(!id)return;let active=true;(async()=>{try{const [p,pr]=await Promise.all([fetchUserById(id),fetchProjects()]);if(!active)return;setPerson(p?.user||p);setProjects((pr?.projects||[]).filter((x:any)=>String(x.owner?.id||x.owner?._id||x.owner)===id).slice(0,12));if(token&&String(user?.id||user?._id)!==id){void recordProfileView(id,token).catch(()=>{});const c=await fetchConnections(token);if(active)setConnections(c?.connections||[])}}catch(e:any){if(active)setError(e?.message||"Unable to load profile")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[id,token,user])
 const relation=useMemo(()=>connections.find(c=>String(c.requester?._id||c.requester)===id||String(c.recipient?._id||c.recipient)===id),[connections,id])
 const connect=async()=>{if(!token)return;setBusy(true);try{await requestConnection(id,token);const c=await fetchConnections(token);setConnections(c?.connections||[])}catch(e:any){setError(e?.message||"Unable to send request")}finally{setBusy(false)}}
 if(isLoading||loading)return <div className="min-h-screen flex items-center justify-center">Loading profile...</div>
 if(!person)return <div className="min-h-screen flex items-center justify-center text-red-600">{error||"Profile not found."}</div>
 const initials=`${person.firstName?.[0]||""}${person.lastName?.[0]||""}`.toUpperCase(); const own=String(user?.id||user?._id)===id
 const links=[{label:"GitHub",icon:Github,url:safeUrl(person.socialLinks?.github)},{label:"LinkedIn",icon:Linkedin,url:safeUrl(person.socialLinks?.linkedin)},{label:"Twitter",icon:Twitter,url:safeUrl(person.socialLinks?.twitter)},{label:"Portfolio",icon:Globe,url:safeUrl(person.socialLinks?.website)}].filter(x=>x.url)
 return <div className="min-h-screen bg-gray-50"><nav className="bg-white border-b sticky top-0 z-50"><div className="max-w-5xl mx-auto px-4 py-4 flex justify-between items-center"><Link href="/dashboard" className="flex items-center gap-2 font-bold text-xl"><Code2 className="text-purple-600"/>DevHeaven</Link><div className="flex gap-2"><Link href="/network"><Button variant="outline">Network</Button></Link>{own&&<Link href="/profile"><Button>Edit profile</Button></Link>}</div></div></nav>
 <main className="max-w-5xl mx-auto px-4 py-8 space-y-6"><Card><CardContent className="pt-6"><div className="flex flex-col md:flex-row gap-6 items-center md:items-start"><Avatar className="h-28 w-28"><AvatarImage src={assetUrl(person.profileImage)}/><AvatarFallback className="text-2xl">{initials}</AvatarFallback></Avatar><div className="flex-1 text-center md:text-left"><div className="flex flex-col md:flex-row md:justify-between gap-4"><div><h1 className="text-3xl font-bold">{person.firstName} {person.lastName}</h1><p className="text-gray-500">@{person.username}</p></div>{!own&&token&&<div className="flex gap-2 justify-center"><Button variant="outline" asChild><Link href={`/messages?user=${encodeURIComponent(id)}`}><MessageSquare className="h-4 w-4 mr-2"/>Message</Link></Button>{relation?.status==="accepted"?<Button variant="outline" disabled><UserCheck className="h-4 w-4 mr-2"/>Connected</Button>:relation?.status==="pending"?<Button variant="outline" disabled><Clock3 className="h-4 w-4 mr-2"/>Pending</Button>:<Button onClick={()=>void connect()} disabled={busy}><UserPlus className="h-4 w-4 mr-2"/>{busy?"Sending...":"Connect"}</Button>}</div>}</div><p className="mt-4 text-gray-700 whitespace-pre-wrap">{person.bio||"This developer has not added a bio yet."}</p><div className="mt-4 flex flex-wrap gap-4 text-sm text-gray-500">{person.location&&<span className="flex gap-1 items-center"><MapPin className="h-4 w-4"/>{person.location}</span>}{person.experience!=null&&<span className="flex gap-1 items-center"><Briefcase className="h-4 w-4"/>{person.experience} years experience</span>}{person.createdAt&&<span className="flex gap-1 items-center"><Calendar className="h-4 w-4"/>Joined {formatLocalDateTime(person.createdAt)}</span>}</div><div className="mt-4 flex flex-wrap gap-2">{(person.skills||[]).map((s:string)=><Badge key={s} variant="secondary">{s}</Badge>)}</div>{links.length>0&&<div className="mt-5 flex flex-wrap gap-3">{links.map(({label,icon:Icon,url})=><a key={label} href={url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-md border bg-white px-3 py-2 text-sm"><Icon className="h-4 w-4"/>{label}</a>)}</div>}</div></div></CardContent></Card>
 {error&&<div className="rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</div>}<Card><CardHeader><CardTitle>Projects ({projects.length})</CardTitle></CardHeader><CardContent>{projects.length===0?<p className="text-sm text-gray-500">No public projects yet.</p>:<div className="grid md:grid-cols-2 gap-4">{projects.map(p=><div key={p.id||p._id} className="rounded-lg border p-4"><h3 className="font-semibold">{p.title}</h3><p className="text-sm text-gray-600 mt-2 line-clamp-3">{p.description}</p><div className="flex flex-wrap gap-1 mt-3">{(p.techStack||[]).map((t:string)=><Badge key={t} variant="outline" className="text-xs">{t}</Badge>)}</div><div className="flex gap-2 mt-4">{p.githubUrl&&<Button size="sm" variant="outline" asChild><a href={p.githubUrl} target="_blank" rel="noopener noreferrer"><Github className="h-4 w-4 mr-1"/>Code</a></Button>}{p.liveUrl&&<Button size="sm" asChild><a href={p.liveUrl} target="_blank" rel="noopener noreferrer">Live demo</a></Button>}</div></div>)}</div>}</CardContent></Card></main></div>
}
