"use client";
import { useState, useEffect, useMemo } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Input } from "@/components/ui/input";
import { Heart, MessageCircle, Share2, Code2, Search, Plus, Bell, Trash2, X } from "lucide-react";
import Link from "next/link";
import { fetchPosts, createPost, likePost, fetchProjects, fetchUserById, assetUrl, fetchUnreadMessageCount, addComment, deletePost, deleteComment, fetchNotifications, markNotificationRead, markAllNotificationsRead } from "@/lib/api";
import { useAuth } from "@/contexts/AuthContext";
import { ConnectionStatus } from "@/components/ConnectionStatus";

export default function Dashboard() {
  const { user, token, isLoading } = useAuth();
  const [posts, setPosts] = useState<any[]>([]), [projectCount, setProjectCount] = useState(0), [profileViewCount, setProfileViewCount] = useState(0), [unreadMessages, setUnreadMessages] = useState(0);
  const [notifications, setNotifications] = useState<any[]>([]), [showNotifications, setShowNotifications] = useState(false);
  const [newPost, setNewPost] = useState({ title: "", content: "" }), [loading, setLoading] = useState(false), [error, setError] = useState(""), [searchTerm, setSearchTerm] = useState("");
  const [selectedPost, setSelectedPost] = useState<any | null>(null), [commentText, setCommentText] = useState(""), [commentLoading, setCommentLoading] = useState(false), [deletingPostId, setDeletingPostId] = useState<string | null>(null), [deletingCommentId, setDeletingCommentId] = useState<string | null>(null);
  const router = useRouter();
  const visiblePosts = useMemo(() => { const t = searchTerm.trim().toLowerCase(); return t ? posts.filter(p => `${p.title||""} ${p.content||""} ${p.author?.firstName||""} ${p.author?.lastName||""}`.toLowerCase().includes(t)) : posts; }, [posts, searchTerm]);
  const unreadNotifications = notifications.filter(n => !n.read).length;
  useEffect(() => { if (!isLoading && !user) router.push("/auth/login"); if (user) void loadPosts(); }, [user, isLoading, router]);
  useEffect(() => { if (!user || !token) return; let active=true; const load=async()=>{try{const [p,u,n,m]=await Promise.all([fetchProjects(),fetchUserById(String(user.id)),fetchNotifications(token),fetchUnreadMessageCount(token)]); const ps=Array.isArray(p?.projects)?p.projects:[]; setProjectCount(ps.filter((x:any)=>String(x.owner?.id||x.owner?._id||x.userId||x.user?._id||"")===String(user.id)).length); setProfileViewCount(Number(u?.profileViewCount)||0); if(active){setNotifications(Array.isArray(n?.notifications)?n.notifications:Array.isArray(n)?n:[]);setUnreadMessages(Math.max(0,Number(m?.count)||0));}}catch(e){console.error(e)}}; void load(); const timer=window.setInterval(load,15000); return()=>{active=false;window.clearInterval(timer)}; },[user,token]);
  const loadPosts=async()=>{try{const d=await fetchPosts();setPosts(Array.isArray(d)?d:[]);setError("")}catch(e){console.error(e);setError("Unable to load posts.")}};
  const handleCreatePost=async(e:React.FormEvent)=>{e.preventDefault();if(!token||!newPost.title.trim()||!newPost.content.trim())return;setLoading(true);try{await createPost(newPost,token);setNewPost({title:"",content:""});await loadPosts()}catch(e){setError(e instanceof Error?e.message:"Unable to create post.")}finally{setLoading(false)}};
  const handleLike=async(id:string)=>{if(!token)return;try{await likePost(id,token);await loadPosts();const p=(await fetchPosts()).find((x:any)=>String(x._id)===String(id));if(p)setSelectedPost(p)}catch{setError("Failed to like post.")}};
  const handleAddComment=async(id:string)=>{if(!token||!commentText.trim())return;setCommentLoading(true);try{await addComment(id,commentText.trim(),token);setCommentText("");await loadPosts();const p=(await fetchPosts()).find((x:any)=>String(x._id)===String(id));if(p)setSelectedPost(p)}catch(e){setError(e instanceof Error?e.message:"Unable to add comment.")}finally{setCommentLoading(false)}};
  const handleDeletePost=async(id:string)=>{if(!token||!window.confirm("Delete this post? This cannot be undone."))return;setDeletingPostId(id);try{await deletePost(id,token);setPosts(x=>x.filter(p=>String(p._id)!==String(id)));if(selectedPost?._id===id)setSelectedPost(null)}catch(e){setError(e instanceof Error?e.message:"Unable to delete post.")}finally{setDeletingPostId(null)}};
  const handleDeleteComment=async(pid:string,cid:string)=>{if(!token||!window.confirm("Delete this comment?"))return;setDeletingCommentId(cid);try{await deleteComment(pid,cid,token);const d=await fetchPosts();const list=Array.isArray(d)?d:[];setPosts(list);setSelectedPost(list.find(p=>String(p._id)===String(pid))||null)}catch(e){setError(e instanceof Error?e.message:"Unable to delete comment.")}finally{setDeletingCommentId(null)}};
  const markOne=async(n:any)=>{if(!token)return;try{await markNotificationRead(String(n._id),token);setNotifications(x=>x.map(a=>String(a._id)===String(n._id)?{...a,read:true}:a));if(n.link)router.push(n.link)}catch(e){console.error(e)}};
  const markAll=async()=>{if(!token)return;try{await markAllNotificationsRead(token);setNotifications(x=>x.map(n=>({...n,read:true})))}catch(e){console.error(e)}};
  if(isLoading)return <div className="min-h-screen flex items-center justify-center">Loading...</div>; if(!user)return null;
  const initials=`${user.firstName?.[0]||""}${user.lastName?.[0]||""}`||"U", profileImage=assetUrl(user.profileImage);
  const isOwnPost=(p:any)=>String(p.author?._id||p.author?.id||p.author)===String(user.id), isOwnComment=(c:any)=>String(c.user?._id||c.user?.id||c.user)===String(user.id);
  return <div className="min-h-screen bg-gray-50"><nav className="bg-white border-b sticky top-0 z-50"><div className="max-w-7xl mx-auto px-4 py-4 flex justify-between items-center"><Link href="/" className="flex items-center gap-2"><Code2 className="h-8 w-8 text-purple-600"/><span className="text-2xl font-bold">DevHeaven</span></Link><div className="hidden md:flex gap-6"><Link href="/dashboard" className="text-purple-600 font-medium">Feed</Link><Link href="/projects">Projects</Link><Link href="/resources">Resources</Link><Link href="/recruiters">Jobs</Link></div><div className="flex items-center gap-3"><ConnectionStatus/><div className="relative hidden sm:block"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 h-4 w-4"/><Input placeholder="Search posts..." className="pl-10 w-64" value={searchTerm} onChange={e=>setSearchTerm(e.target.value)}/></div><Button size="sm" onClick={()=>document.getElementById("create-post")?.scrollIntoView({behavior:"smooth"})}><Plus className="h-4 w-4 mr-2"/>Post</Button><div className="relative"><button type="button" aria-label="Notifications" onClick={()=>setShowNotifications(x=>!x)} className="relative text-gray-600 hover:text-purple-600"><Bell className="h-6 w-6"/>{unreadNotifications>0&&<span className="absolute -right-2 -top-2 min-w-5 h-5 px-1 rounded-full bg-red-500 text-white text-[10px] font-bold flex items-center justify-center ring-2 ring-white">{unreadNotifications>99?"99+":unreadNotifications}</span>}</button>{showNotifications&&<Card className="absolute right-0 mt-3 w-80 sm:w-96 shadow-xl z-50"><CardHeader className="flex flex-row items-center justify-between pb-3"><span className="font-semibold">Notifications</span><button onClick={markAll} className="text-xs text-purple-600">Mark all as read</button></CardHeader><CardContent className="p-0 max-h-96 overflow-y-auto">{notifications.length===0?<p className="p-5 text-sm text-gray-500">No notifications yet.</p>:notifications.map(n=><button key={n._id} onClick={()=>markOne(n)} className={`w-full text-left px-4 py-3 border-t hover:bg-gray-50 ${!n.read?"bg-purple-50":""}`}><div className="text-sm font-medium">{n.title||n.message||"New activity"}</div><div className="text-xs text-gray-500 mt-1">{n.createdAt?new Date(n.createdAt).toLocaleString():""}</div></button>)}</CardContent></Card>}</div><Link href="/messages" className="relative flex h-8 w-8 items-center justify-center rounded-full text-gray-600 hover:bg-gray-100"><MessageCircle className="h-6 w-6"/>{unreadMessages>0&&<span className="absolute -right-1 -top-1 min-w-5 h-5 px-1 rounded-full bg-red-500 text-white text-[10px] font-bold flex items-center justify-center ring-2 ring-white">{unreadMessages>99?"99+":unreadMessages}</span>}</Link><Link href="/profile"><Avatar className="h-8 w-8"><AvatarImage src={profileImage||"/placeholder.svg"}/><AvatarFallback>{initials}</AvatarFallback></Avatar></Link></div></div></nav>
  <main className="max-w-7xl mx-auto px-4 py-8"><div className="grid grid-cols-1 lg:grid-cols-4 gap-8"><aside><Card><CardHeader><div className="flex items-center gap-3"><Avatar className="h-12 w-12"><AvatarImage src={profileImage||"/placeholder.svg"}/><AvatarFallback>{initials}</AvatarFallback></Avatar><div><h3 className="font-semibold">{user.firstName} {user.lastName}</h3><p className="text-sm text-gray-600">{user.location||"Developer"}</p></div></div></CardHeader><CardContent><div className="space-y-2 text-sm"><div className="flex justify-between"><span>Projects</span><b>{projectCount}</b></div><div className="flex justify-between"><span>Profile Views</span><b>{profileViewCount}</b></div></div></CardContent></Card></aside><section className="lg:col-span-2 space-y-6"><Card id="create-post"><CardHeader><h2 className="font-semibold">Create a post</h2></CardHeader><CardContent><form onSubmit={handleCreatePost} className="space-y-3"><Input placeholder="Post title" value={newPost.title} onChange={e=>setNewPost({...newPost,title:e.target.value})}/><textarea className="w-full min-h-24 rounded-md border p-3" placeholder="Share something with developers..." value={newPost.content} onChange={e=>setNewPost({...newPost,content:e.target.value})}/><Button type="submit" disabled={loading}>{loading?"Posting...":"Publish"}</Button></form></CardContent></Card>{error&&<div className="rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</div>}{visiblePosts.map(post=><Card key={post._id} className="cursor-pointer hover:shadow-md" onClick={()=>setSelectedPost(post)}><CardContent className="p-6"><div className="flex justify-between"><div className="flex gap-3"><Avatar><AvatarImage src={assetUrl(post.author?.profileImage)||"/placeholder.svg"}/><AvatarFallback>{post.author?.firstName?.[0]||"U"}</AvatarFallback></Avatar><div><b>{post.author?.firstName} {post.author?.lastName}</b><p className="text-sm text-gray-500">{post.title}</p></div></div>{isOwnPost(post)&&<Button variant="ghost" size="icon" disabled={deletingPostId===post._id} onClick={e=>{e.stopPropagation();void handleDeletePost(String(post._id))}}><Trash2 className="h-4 w-4 text-red-500"/></Button>}</div><p className="mt-4 text-gray-700 whitespace-pre-wrap">{post.content}</p><div className="flex gap-5 mt-5 text-sm text-gray-500"><span><Heart className="inline h-4 w-4"/> {post.likes?.length||0}</span><span><MessageCircle className="inline h-4 w-4"/> {post.comments?.length||0}</span><span><Share2 className="inline h-4 w-4"/> Share</span></div></CardContent></Card>)}</section></div></main>
  {selectedPost&&<div className="fixed inset-0 z-[60] bg-black/40 flex items-center justify-center p-4" onClick={()=>setSelectedPost(null)}><Card className="w-full max-w-2xl max-h-[90vh] overflow-y-auto" onClick={e=>e.stopPropagation()}><CardHeader className="flex flex-row justify-between"><span className="font-semibold">{selectedPost.title}</span><button onClick={()=>setSelectedPost(null)}><X/></button></CardHeader><CardContent><p className="whitespace-pre-wrap">{selectedPost.content}</p><div className="flex gap-4 mt-5"><Button variant="ghost" onClick={()=>void handleLike(String(selectedPost._id))}><Heart className="mr-2 h-4 w-4"/>Like {selectedPost.likes?.length||0}</Button>{isOwnPost(selectedPost)&&<Button variant="ghost" onClick={()=>void handleDeletePost(String(selectedPost._id))} disabled={!!deletingPostId}><Trash2 className="mr-2 h-4 w-4 text-red-500"/>Delete</Button>}</div><div className="mt-6 space-y-3">{(selectedPost.comments||[]).map((c:any)=><div key={c._id} className="rounded-lg bg-gray-50 p-3 flex justify-between gap-3"><div><b className="text-sm">{c.user?.firstName} {c.user?.lastName}</b><p className="text-sm mt-1">{c.text}</p></div>{isOwnComment(c)&&<button onClick={()=>void handleDeleteComment(String(selectedPost._id),String(c._id))} disabled={deletingCommentId===String(c._id)}><Trash2 className="h-4 w-4 text-red-500"/></button>}</div>)}</div><div className="mt-5 flex gap-2"><Input placeholder="Write a comment..." value={commentText} onChange={e=>setCommentText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void handleAddComment(String(selectedPost._id))}}}/><Button onClick={()=>void handleAddComment(String(selectedPost._id))} disabled={commentLoading||!commentText.trim()}>Comment</Button></div></CardContent></Card></div>}
  </div>;
}